import { FormBuilder } from './formBuilder'
export type { CheckboxInputProps, CheckboxInputValueType } from 'inputs/checkbox/types'
export type { CustomInputProps, CustomInputValueType } from 'inputs/custom/types'
export type { DateInputProps, DateInputValueType } from 'inputs/date/types'
export type { DatetimeInputProps, DatetimeInputValueType } from 'inputs/datetime/types'
export type { FileInputProps, FileInputValueType } from 'inputs/file/types'
export type { GroupInputProps, GroupInputValueType } from 'inputs/group/types'
export type { ItemsInputProps, ItemsInputValueType } from 'inputs/items/types'
export type { MaskInputProps, MaskInputValueType } from 'inputs/mask/types'
export type { MobileInputProps, MobileInputValueType } from 'inputs/mobile/types'
export type { NumberInputProps, NumberInputValueType } from 'inputs/number/types'
export type { OtpInputProps, OtpInputValueType } from 'inputs/otp/types'
export type { PasswordInputProps, PasswordInputValueType } from 'inputs/password/types'
export type { SelectInputProps, SelectInputValueType } from 'inputs/select/types'
export type { TextInputProps, TextInputValueType } from 'inputs/text/types'
export type { TimeInputProps, TimeInputValueType } from 'inputs/time/types'
export type { ToggleInputProps, ToggleInputValueType } from 'inputs/toggle/types'
export type { AutocompleteInputProps, AutocompleteOptionType, AutocompleteValueType } from './inputs/autocomplete/types'

export { FormBuilder }
export default FormBuilder
// export { AutocompleteInput } from './inputs/autocomplete/index'
// export { CheckboxInput } from './inputs/checkbox'
// export { CustomInput } from './inputs/custom'
// export { DateInput } from './inputs/date'
// export { DatetimeInput } from './inputs/datetime'
// export { FileInput } from './inputs/file'
// export { GroupInput } from './inputs/group'
// export { ItemsInput } from './inputs/items'
// export { MaskInput } from './inputs/mask'
// export { MobileInput } from './inputs/mobile'
// export { NumberInput } from './inputs/number'
// export { OtpInput } from './inputs/otp'
// export { PasswordInput } from './inputs/password'
// export { SelectInput } from './inputs/select'
// export { TextInput } from './inputs/text'
// export { TimeInput } from './inputs/time'
// export { ToggleInput } from './inputs/toggle'
